add step to check go version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,5 +18,8 @@ jobs:
         with:
           go-version: "1.26.0"
 
-      - name: Force Failure
-        run: (exit 1)
+      - name: Check go version
+        run: go version
+    
+    #   - name: Force Failure
+    #     run: (exit 1)
